fix(cli): fix broken mDNS resolving on macOS with go1.19
While testing, I noticed that localias installed via homebrew
was unable to serve .local aliases over mDNS:

```
❯ /opt/homebrew/bin/localias run
[ ... snip ... ]
error: failed to find local IP: lookup pld-mbp-22.local on 8.8.8.8:53: no such host
```

The problem is that the release binaries were being built with go1.19,
which does not use the macOS system DNS resolution algorithm. Locally, I
had been developing with go1.20, which does. See https://danp.net/posts/macos-dns-change-in-go-1-20/
for more information on the differences between go1.19 and go1.20.

To fix this issue, this commit:

- Updates the release binary workflow to use go1.20
- Updates the localias server code to warn but continue if the mDNS
  server cannot be started, so that mDNS errors do not prevent you
  from successfully using localias.
- Adds some log lines showing which aliases are being served over mDNS
  when they are successfully being served. This should make debugging
  easier in the future.